### ISSUE TITLE
no result.   primary.cds primary.pep  empty

### ISSUE THREAD

**Issue by woshi0655** [yanyew/SynGAP#16]
Hello, when I run syngap, I get an empty result. The primary.id file is fine, however the primary.cds and primary.pep files are both empty when I check them. What took place? Below is a display of the log.

[08/16/24 12:45:53] DEBUG    Load file `VpXY.VpXX.last.filtered`      base.py:36
                    DEBUG    A total of 0 BLAST imported from     synteny.py:277
                             `VpXY.VpXX.last.filtered`.                         
                    DEBUG    Chaining distance = 20              synteny.py:1794
                    DEBUG    Load file `VpXY.VpXX.anchors`            base.py:36
                    DEBUG    A total of 0 anchor was found.      synteny.py:1371
                             Aborted.                                           
Traceback (most recent call last):
  File "/home/geta/miniconda3/envs/syngap/lib/python3.10/site-packages/jcvi/compara/catalog.py", line 742
, in ortholog
    scan(dargs)
  File "/home/geta/miniconda3/envs/syngap/lib/python3.10/site-packages/jcvi/compara/synteny.py", line 181
1, in scan
    summary([anchor_file])
  File "/home/geta/miniconda3/envs/syngap/lib/python3.10/site-packages/jcvi/compara/synteny.py", line 137
2, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.

The above exception was the direct cause of the following exception:

**Comment by yanyew** [comment]
Thank you for trying SynGAP and sorry for the late respose.
If `the primary.id file is fine, however the primary.cds and primary.pep files are both empty`, it may happen while the `seqkit` software wasn't configured correctly. Can you show me the file under `.../workspace/renamed_id`?

**Comment by woshi0655** [comment]
![8367fbc319a437bccc08f0b54ce2ea6](https://github.com/user-attachments/assets/44077bc7-ddeb-4971-b106-1fed7df2d05a)

![dc0a9eb054e3d9cac9fbefe646357ea](https://github.com/user-attachments/assets/ca46a12e-e340-42c1-a4da-ae6c92c5c43d)
![77c55d1d133fa97dcacdb7758b6c7e3](https://github.com/user-attachments/assets/76a6e29d-e62f-4746-a96a-a65c6b3e6e35)
here is the file in folder renamed_id.

**Comment by yanyew** [comment]
> ![8367fbc319a437bccc08f0b54ce2ea6](https://private-user-images.githubusercontent.com/29584533/358850749-44077bc7-ddeb-4971-b106-1fed7df2d05a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDUwNzYsIm5iZiI6MTcyMzkwNDc3NiwicGF0aCI6Ii8yOTU4NDUzMy8zNTg4NTA3NDktNDQwNzdiYzctZGRlYi00OTcxLWIxMDYtMWZlZDdkZjJkMDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE0MjYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZjEzOWUxODE2MTY4YTVkNDg5ODkxODZlMDBiYmUzMzJlMGMwMDg3ZWJhMGRkYjg0MDAyM2I5MzMxOWEwZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cYSEVt8SiujHH_pRbd6B8OWZjN0gO5MaPMFmq9w94XU)
> 
> ![dc0a9eb054e3d9cac9fbefe646357ea](https://private-user-images.githubusercontent.com/29584533/358850921-ca46a12e-e340-42c1-a4da-ae6c92c5c43d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDUwNzYsIm5iZiI6MTcyMzkwNDc3NiwicGF0aCI6Ii8yOTU4NDUzMy8zNTg4NTA5MjEtY2E0NmExMmUtZTM0MC00MmMxLWE0ZGEtYWU2YzkyYzVjNDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE0MjYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiN2NhNjQzNDQ2NTU0YjViOTBhZTZlMjUxYzc1NTI2OWJkZjMzNGMwNzcyMGNlMTc4NDM2OWIxODIwOTBmYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.arPQMKpjdArIw2LXePAXLgreJlH67S0ic7ZSgj0kWMQ) ![77c55d1d133fa97dcacdb7758b6c7e3](https://private-user-images.githubusercontent.com/29584533/358850925-76a6e29d-e62f-4746-a96a-a65c6b3e6e35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDUwNzYsIm5iZiI6MTcyMzkwNDc3NiwicGF0aCI6Ii8yOTU4NDUzMy8zNTg4NTA5MjUtNzZhNmUyOWQtZTYyZi00NzQ2LWE5NmEtYTY1YzZiM2U2ZTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE0MjYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZTUyYzFhMTlkZTAxMGU2NmU1YzFmNGYwZTM1NDE5YjA3YzI4NDBkNGE1NjI0NjJmYTI4NGY4YWUxNzU3MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7JvE_WMTAYPRW4URkPSzM5U7ZdJa-kbxA4bUSN2xFMU) here is the file in folder renamed_id.

There is something wrong with the `.rename.pep` and `.rename.cds` files. Is it possible for you to send me the original `.gff3` file to check the possible non-standard formats

**Comment by woshi0655** [comment]
Thank you , here is the two gff3 file I used.













At 2024-08-17 22:33:18, "yanyew" ***@***.***> wrote:

here is the file in folder renamed_id.

There is something wrong with the .rename.pep and .rename.cds files. Is it possible for you to send me the original .gff3 file to check the possible non-standard formats

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易126邮箱发来的超大附件推荐客户端极速下载
15.gff3 (30.3M, 2024年10月6日 22:36 到期)
下载
final.gff3 (29.45M, 2024年10月6日 22:36 到期)
下载

**Comment by yanyew** [comment]
> Thank you , here is the two gff3 file I used. At 2024-08-17 22:33:18, "yanyew" ***@***.***> wrote: here is the file in folder renamed_id. There is something wrong with the .rename.pep and .rename.cds files. Is it possible for you to send me the original .gff3 file to check the possible non-standard formats — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***> 从网易126邮箱发来的超大附件推荐客户端极速下载 15.gff3 (30.3M, 2024年10月6日 22:36 到期) 下载 final.gff3 (29.45M, 2024年10月6日 22:36 到期) 下载

Sorry, the download links didn't work. You can send the files to my Email 360875601@qq.com directly.

**Comment by yanyew** [comment]
> Thank you , here is the two gff3 file I used. At 2024-08-17 22:33:18, "yanyew" ***@***.***> wrote: here is the file in folder renamed_id. There is something wrong with the .rename.pep and .rename.cds files. Is it possible for you to send me the original .gff3 file to check the possible non-standard formats — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***> 从网易126邮箱发来的超大附件推荐客户端极速下载 15.gff3 (30.3M, 2024年10月6日 22:36 到期) 下载 final.gff3 (29.45M, 2024年10月6日 22:36 到期) 下载

Sorry, the download links didn't work. You can send the files to my Email 360875601@qq.com directly.

**Comment by yanyew** [comment]
It seems that the `gff` file didn't contain non-standard formats. Can you snd me the `.fasta` file of genomes?

**Comment by yanyew** [comment]
> Thank you , here is the two gff3 file I used. At 2024-08-17 22:33:18, "yanyew" ***@***.***> wrote: here is the file in folder renamed_id. There is something wrong with the .rename.pep and .rename.cds files. Is it possible for you to send me the original .gff3 file to check the possible non-standard formats — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***> 从网易126邮箱发来的超大附件推荐客户端极速下载 15.gff3 (30.3M, 2024年10月6日 22:36 到期) 下载 final.gff3 (29.45M, 2024年10月6日 22:36 到期) 下载

Sorry for the late reply. I found that this error was caused by the wrong `Parent` information in your `gff3` files.
The `Parent` for the `CDS`s are the `gene` ID rather than the `mRNA` ID. You may need to reformat your `gff3` files.
![image](https://github.com/user-attachments/assets/784c1a8e-8bd7-4a65-a378-0c7962f75adb)
