### ISSUE TITLE
There is no latest version of docker image!

### ISSUE THREAD

**Issue by ChuanzhengWei** [yanyew/SynGAP#18]
Hi,

I recently attempted to pull the Docker image yanyew/syngap:1.2.3 but encountered an error. Upon checking Docker Hub, I noticed that the latest available version is 1.1.0. However, according to Bioconda, the most recent version is 1.2.5.

Would it be possible for you to upload the latest Docker image corresponding to the latest version? This would be greatly beneficial for those of us relying on the most current features and updates.

Best regards!

**Comment by yanyew** [comment]
Thanks for trying SynGAP~ I wiil upload the new version Docker image

**Comment by yanyew** [comment]
I have upload the 1.2.5 Docker images. You can try it.

**Comment by ChuanzhengWei** [comment]
Thanks!
