### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by PengfeiInTuebingen** [yanyew/SynGAP#21]
Hi,
Super cool tool!
I have trouble to install it by conda or mamba,  i can do singularity pull docker://.., but i can run it by singularity exec docker://...,
any suggestions for installation?
Thanks in advance!
Best,
PF

**Comment by yanyew** [comment]
Thanks for trying SynGAP!
What's the details about the problem you met to install it by conda?
As for the iamge, I will provide one version for singularity later.

**Comment by PengfeiInTuebingen** [comment]
hi there,
Command i used for installation: 
/
error i received: 

/

**Comment by PengfeiInTuebingen** [comment]
solved! 
Thanks!
