### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '' in Rlabel.py

### ISSUE THREAD

**Issue by LeoHongboWANG** [yanyew/SynGAP#23]
Hi,

Thank you for developing this outstanding tool! I am trying to SynGAP v1.2.5 and I encountered a ValueError: invalid literal for int() with base 10: '' error when running the syngap dual command.

Steps to Reproduce:

Please provide detailed steps to reproduce the issue:

Run the following command:
syngap dual --sp2fa 3sp_sp2fa.fa --sp2gff  3sp_sp2gff_file.gff3 --sp1fa 9sp1fa_file.fa --sp1gff 9sp_sp1gff_file.gff3 --threads 32 --process miniprot --sp1=9sp --sp2=3sp
Observe the following error:
[INFO] Running Done!
[INFO] Calculating and labeling R value for modified annotations of 9sp, please wait ...
[INFO] Running Done!
[INFO] Calculating and labeling R value for modified annotations of 3sp, please wait ...
Traceback (most recent call last):
  File "/opt/miniconda3/envs/syngap/bin/syngap", line 11, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/syngap/bin/SynGAP.py", line 263, in main
    args.func(args)
  File "/opt/miniconda3/envs/syngap/bin/dual.py", line 42, in dual
    SynGAP_miniprot.SynGAP(
  File "/opt/miniconda3/envs/syngap/bin/scripts/SynGAP_miniprot.py", line 209, in SynGAP
    Rlabel.Rlabel(str(sp2), sp2blockRbed, sp1bed, sp1blockRbed, sp2modgff_filtered, sp2R, sp2modgff_R)
  File "/opt/miniconda3/envs/syngap/bin/scripts/Rlabel.py", line 102, in Rlabel
    reformatneedle(path, sp, n)
  File "/opt/miniconda3/envs/syngap/bin/scripts/Rlabel.py", line 74, in reformatneedle
    Identity = int(Identity_counts) / int(Length)
ValueError: invalid literal for int() with base 10: ''

How could I figure out?
Thank you very much

Best

**Comment by yanyew** [comment]
Thanks for trying SynGAP~
I didn't meet the same issue in my tests. Would you mind offering the source files that you used to me for trouble shooting?

**Comment by LeoHongboWANG** [comment]
Hi @yanyew,

Thank you so much for your quick response!

I appreciate your offer to troubleshoot the issue. I tried running SynGAP using the Conda installation today, and it worked successfully with excellent results. However, I still encountered issues when running it with Singularity yesterday.

Thank you again for your support and for developing such an outstanding tool!
